# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b6c0837ddfd180d630f6fdfc535d804e"
name = "active-shopify"
handle = "active-shopify"
application_url = "https://active-shopify.torudigital.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "active-shopify.torudigital.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_inventory,write_draft_orders"

[auth]
redirect_urls = [
  "https://desire-occur-helped-ips.trycloudflare.com/auth/callback",
  "https://desire-occur-helped-ips.trycloudflare.com/auth/shopify/callback",
  "https://desire-occur-helped-ips.trycloudflare.com/api/auth/callback",
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
